import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AreaChart,Area,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {Activity,ArrowDownRight,ArrowUpRight,BarChart3,Bell,BookOpen,Briefcase,ChevronDown,Clock3,Command,CreditCard,Download,Eye,EyeOff,History,Home,LogOut,Menu,MoreHorizontal,Plus,QrCode,Search,Upload,Settings,ShieldCheck,Star,TrendingDown,TrendingUp,Wallet,X,Zap} from 'lucide-react';
import './styles.css';

const assets=[
 {symbol:'RELIANCE',name:'Reliance Industries',price:2938.45,change:1.84,sector:'Energy'},
 {symbol:'TCS',name:'Tata Consultancy Services',price:4125.20,change:-0.62,sector:'IT'},
 {symbol:'HDFCBANK',name:'HDFC Bank',price:1742.80,change:.91,sector:'Banking'},
 {symbol:'INFY',name:'Infosys',price:1538.10,change:2.31,sector:'IT'},
 {symbol:'ICICIBANK',name:'ICICI Bank',price:1324.55,change:-.18,sector:'Banking'},
 {symbol:'BHARTIARTL',name:'Bharti Airtel',price:1864.90,change:1.12,sector:'Telecom'},
 {symbol:'SBIN',name:'State Bank of India',price:872.65,change:1.43,sector:'Banking'},
 {symbol:'ITC',name:'ITC Limited',price:487.35,change:-.28,sector:'FMCG'},
 {symbol:'LT',name:'Larsen & Toubro',price:3824.70,change:.76,sector:'Industrials'}
];
const candles=[32,35,34,39,37,43,42,48,46,52,50,57,55,63,61,67,65,71,69,76,74,81,79,86,83,90,88,95,92,99].map((v,i)=>({t:`${9+Math.floor(i/4)}:${String(15+(i%4)*15).padStart(2,'0')}`,value:v}));
const holdings=[{s:'RELIANCE',q:24,avg:2701.2},{s:'TCS',q:10,avg:3978.4},{s:'HDFCBANK',q:32,avg:1699.1},{s:'INFY',q:18,avg:1428.5},{s:'BHARTIARTL',q:14,avg:1770.3}];
const fmt=n=>n.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});

function App(){
 const [view,setView]=useState('home'); const [selected,setSelected]=useState(assets[0]); const [side,setSide]=useState('buy'); const [qty,setQty]=useState(10); const [orderType,setOrderType]=useState('Market'); const [limit,setLimit]=useState(selected.price); const [cash,setCash]=useState(125000); const [orders,setOrders]=useState([]); const [watch,setWatch]=useState(['RELIANCE','TCS','HDFCBANK','INFY']); const [query,setQuery]=useState(''); const [modal,setModal]=useState(null); const [showBalance,setShowBalance]=useState(true); const [mobile,setMobile]=useState(false); const [timeframe,setTimeframe]=useState('1D');
 const filtered=assets.filter(a=>(a.symbol+' '+a.name).toLowerCase().includes(query.toLowerCase()));
 const price=orderType==='Limit'?Number(limit)||selected.price:selected.price; const value=Math.max(1,Number(qty)||1)*price;
 const place=()=>{const q=Math.max(1,Number(qty)||1); if(side==='buy'&&value>cash){setModal('insufficient');return} setCash(c=>side==='buy'?c-value:c+value);setOrders(o=>[{id:Date.now(),symbol:selected.symbol,side,qty:q,price,status:'Executed',type:orderType,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})},...o]);setModal('success')};
 const toggleWatch=()=>setWatch(w=>w.includes(selected.symbol)?w.filter(x=>x!==selected.symbol):[...w,selected.symbol]);
 return <div className="shell">
  <header className="top"><div className="brand"><div className="brandmark"><Activity size={20}/></div><b>Pulse<span>Trade</span></b></div><div className="market"><i/> NSE <strong>25,184.30</strong><span>+0.72%</span></div><div className="global-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search stocks, ETFs, indices..."/><kbd>⌘ K</kbd></div><div className="top-right"><button className="icon" title="Notifications"><Bell size={18}/><em/></button><button className="avatar">AK</button><button className="mobile-menu icon" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></header>
  <aside className={mobile?'nav open':'nav'}><div className="nav-label">WORKSPACE</div>{[[Home,'Overview','home'],[BarChart3,'Markets','markets'],[Briefcase,'Portfolio','portfolio'],[History,'Orders','orders'],[Wallet,'Funds','funds']].map(([I,l,v])=><button className={view===v?'active':''} onClick={()=>{setView(v);setMobile(false)}} key={v}><I size={18}/>{l}</button>)}<div className="nav-label spaced">TOOLS</div><button><Star size={18}/>Watchlist</button><button><BookOpen size={18}/>Research</button><button><Settings size={18}/>Settings</button><div className="nav-bottom"><div className="demo"><ShieldCheck size={16}/><div><b>Demo account</b><small>Paper trading enabled</small></div></div><button><LogOut size={17}/>Sign out</button></div></aside>
  <main className="main">
   {view==='home'&&<><section className="welcome"><div><p className="overline">THURSDAY · 10 SEP 2026</p><h1>Good afternoon, Adnan.</h1><p>Markets are moving. Here's your trading cockpit.</p></div><button className="fund" onClick={()=>setModal('funds')}><Plus size={17}/> Add money</button></section>
   <section className="metric-grid"><Metric label="Total portfolio" value={showBalance?'₹8,42,680':'•••••••'} delta="+₹14,280.40" pct="+1.72%" up icon={<Briefcase/>}/><Metric label="Available cash" value={showBalance?`₹${fmt(cash)}`:'•••••••'} delta="Ready to trade" icon={<Wallet/>}/><Metric label="Today's P&L" value="+₹6,482.25" delta="vs yesterday" pct="+0.77%" up icon={<TrendingUp/>}/><Metric label="Invested" value="₹7,17,540" delta="85.1% allocated" icon={<Activity/>}/></section>
   <div className="content-grid"><section className="card chart-card"><div className="card-head"><div><p className="overline">MARKET</p><div className="instrument"><div className="asset-logo">{selected.symbol.slice(0,1)}</div><div><h2>{selected.symbol} <small>NSE</small></h2><p>{selected.name}</p></div></div></div><div className="quote"><b>₹{fmt(selected.price)}</b><span className={selected.change>=0?'positive':'negative'}>{selected.change>=0?'+':''}{selected.change}%</span><button className={watch.includes(selected.symbol)?'watch-btn on':'watch-btn'} onClick={toggleWatch}><Star size={17} fill={watch.includes(selected.symbol)?'currentColor':'none'}/></button></div></div><div className="chart-toolbar"><div>{['1D','1W','1M','3M','1Y','5Y'].map(x=><button className={timeframe===x?'chosen':''} onClick={()=>setTimeframe(x)} key={x}>{x}</button>)}</div><button className="compare"><Activity size={14}/> Compare</button></div><div className="chart"><ResponsiveContainer><AreaChart data={candles}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopOpacity=".35"/><stop offset="1" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="t" hide/><YAxis hide domain={['dataMin - 5','dataMax + 5']}/><Tooltip contentStyle={{background:'#121925',border:'1px solid #263246',borderRadius:10,color:'#fff'}} formatter={(v)=>[`₹${v.toFixed(2)}`,'Price']}/><Area type="monotone" dataKey="value" strokeWidth={2.5} fill="url(#fill)" stroke="currentColor"/></AreaChart></ResponsiveContainer></div><div className="chart-meta"><span>09:15</span><span>11:00</span><span>13:00</span><span>15:30</span></div><div className="ohlc"><span>Open <b>₹2,911.20</b></span><span>High <b>₹2,956.80</b></span><span>Low <b>₹2,904.10</b></span><span>Prev. close <b>₹2,885.35</b></span></div></section>
   <section className="card watch-card"><div className="card-head"><div><p className="overline">WATCHLIST</p><h2>Market movers</h2></div><button className="ghost">Edit</button></div><div className="tabs"><button className="tab active">All</button><button className="tab">Gainers</button><button className="tab">Losers</button></div>{assets.slice(0,7).map(a=><button className={selected.symbol===a.symbol?'watch-row selected':'watch-row'} onClick={()=>{setSelected(a);setLimit(a.price)}} key={a.symbol}><div className="mini-logo">{a.symbol[0]}</div><div className="watch-name"><b>{a.symbol}</b><small>{a.name}</small></div><div className="watch-price"><b>₹{fmt(a.price)}</b><span className={a.change>=0?'positive':'negative'}>{a.change>=0?'+':''}{a.change}%</span></div><ChevronDown size={14} className="chev"/></button>)}</section></div>
   <div className="bottom-grid"><section className="card activity"><div className="card-head"><div><p className="overline">TRADING ACTIVITY</p><h2>Recent orders</h2></div><button className="ghost" onClick={()=>setView('orders')}>View all</button></div>{orders.length===0?<Empty/>:orders.slice(0,5).map(o=><OrderRow o={o} key={o.id}/>)}</section><section className="card order-card"><div className="card-head"><div><p className="overline">ORDER TICKET</p><h2>{selected.symbol}</h2></div><span className="live"><i/> LIVE</span></div><div className="buy-sell"><button className={side==='buy'?'buy active':''} onClick={()=>setSide('buy')}>Buy</button><button className={side==='sell'?'sell active':''} onClick={()=>setSide('sell')}>Sell</button></div><div className="order-type"><span>Order type</span><button onClick={()=>setOrderType(orderType==='Market'?'Limit':'Market')}>{orderType}<ChevronDown size={14}/></button></div><div className="input-label">Quantity</div><div className="number-input"><input type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/><span>SHARES</span></div>{orderType==='Limit'&&<><div className="input-label">Limit price</div><div className="number-input"><input type="number" value={limit} onChange={e=>setLimit(e.target.value)}/><span>₹ INR</span></div></>}<div className="quick"><button onClick={()=>setQty(1)}>1</button><button onClick={()=>setQty(5)}>5</button><button onClick={()=>setQty(10)}>10</button><button onClick={()=>setQty(25)}>25</button><button onClick={()=>setQty(50)}>50</button></div><div className="ticket-total"><span>Estimated value</span><strong>₹{fmt(value)}</strong></div><div className="ticket-total muted-row"><span>Available</span><span>₹{fmt(cash)}</span></div><button className={side==='buy'?'place buy-place':'place sell-place'} onClick={place}>{side==='buy'?<ArrowUpRight size={18}/>:<ArrowDownRight size={18}/>} {side==='buy'?'Buy':'Sell'} {selected.symbol}</button><small className="paper-note">Paper trade only · No real money or securities are transferred</small></section></div></>}
   {view==='markets'&&<Markets assets={assets} onSelect={a=>{setSelected(a);setLimit(a.price);setView('home')}}/>}
   {view==='portfolio'&&<Portfolio/>}
   {view==='orders'&&<Orders orders={orders}/>} 
   {view==='funds'&&<Funds cash={cash} onAdd={()=>setModal('funds')}/>} 
  </main>
  {modal&&<Modal type={modal} close={()=>setModal(null)} cash={cash} onAdd={(n)=>{setCash(c=>c+n);setModal(null)}}/>}
 </div>
}
function Metric({label,value,delta,pct,up,icon}){return <div className="metric"><div className="metric-icon">{icon}</div><p>{label}</p><h3>{value}</h3><span className={up?'positive':''}>{pct&&<>{pct} · </>}{delta}</span></div>}
function Empty(){return <div className="empty"><Clock3 size={23}/><b>No orders yet</b><span>Your paper trades will appear here.</span></div>}
function OrderRow({o}){return <div className="order-row"><div className={o.side==='buy'?'order-icon buy-i':'order-icon sell-i'}>{o.side==='buy'?'B':'S'}</div><div><b>{o.side==='buy'?'Bought':'Sold'} {o.symbol}</b><small>{o.qty} shares · ₹{fmt(o.price)}</small></div><div className="order-status"><b>Executed</b><small>{o.time}</small></div></div>}
function Markets({assets,onSelect}){return <section className="page"><div className="page-title"><div><p className="overline">MARKETS</p><h1>Explore the market</h1><p>Track popular Indian equities and quickly open an order ticket.</p></div><div className="market-summary"><b>NIFTY 50</b><strong>25,184.30</strong><span className="positive">+0.72%</span></div></div><div className="card table-card"><div className="market-filter"><button className="pill active">All stocks</button><button className="pill">Large cap</button><button className="pill">Gainers</button><button className="pill">Losers</button></div><table><thead><tr><th>Instrument</th><th>Sector</th><th>Last price</th><th>Change</th><th>Day range</th><th></th></tr></thead><tbody>{assets.map(a=><tr key={a.symbol}><td><div className="table-stock"><div className="mini-logo">{a.symbol[0]}</div><span><b>{a.symbol}</b><small>{a.name}</small></span></div></td><td>{a.sector}</td><td>₹{fmt(a.price)}</td><td className={a.change>=0?'positive':'negative'}>{a.change>=0?'+':''}{a.change}%</td><td><div className="range"><i style={{width:`${35+Math.abs(a.change)*12}%`}}/></div></td><td><button className="trade-small" onClick={()=>onSelect(a)}>Trade</button></td></tr>)}</tbody></table></div></section>}
function Portfolio(){return <section className="page"><div className="page-title"><div><p className="overline">PORTFOLIO</p><h1>Your investments</h1><p>Track holdings, allocation and performance in one view.</p></div><button className="fund"><Download size={16}/> Export report</button></div><div className="portfolio-cards"><Metric label="Portfolio value" value="₹8,42,680" delta="+1.72% today" up icon={<Briefcase/>}/><Metric label="Invested capital" value="₹7,17,540" delta="85.1% allocated" icon={<Activity/>}/><Metric label="Overall P&L" value="+₹82,410" delta="+10.84%" up icon={<TrendingUp/>}/></div><div className="card table-card"><div className="card-head"><div><p className="overline">HOLDINGS</p><h2>Equity positions</h2></div><span className="tag">5 holdings</span></div><table><thead><tr><th>Stock</th><th>Qty</th><th>Avg. price</th><th>LTP</th><th>Invested</th><th>Current</th><th>P&L</th></tr></thead><tbody>{holdings.map(h=>{const a=assets.find(x=>x.symbol===h.s);const pnl=(a.price-h.avg)*h.q;return <tr key={h.s}><td><div className="table-stock"><div className="mini-logo">{h.s[0]}</div><span><b>{h.s}</b><small>{a.name}</small></span></div></td><td>{h.q}</td><td>₹{fmt(h.avg)}</td><td>₹{fmt(a.price)}</td><td>₹{fmt(h.avg*h.q)}</td><td>₹{fmt(a.price*h.q)}</td><td className={pnl>=0?'positive':'negative'}>{pnl>=0?'+':''}₹{fmt(pnl)}</td></tr>})}</tbody></table></div></section>}
function Orders({orders}){return <section className="page"><div className="page-title"><div><p className="overline">ORDERS</p><h1>Order history</h1><p>Review every paper trade placed from this account.</p></div></div><div className="card table-card"><div className="market-filter"><button className="pill active">All</button><button className="pill">Executed</button><button className="pill">Pending</button><button className="pill">Cancelled</button></div>{orders.length?<table><thead><tr><th>Time</th><th>Instrument</th><th>Side</th><th>Type</th><th>Qty</th><th>Price</th><th>Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.time}</td><td><b>{o.symbol}</b></td><td className={o.side==='buy'?'positive':'negative'}>{o.side.toUpperCase()}</td><td>{o.type}</td><td>{o.qty}</td><td>₹{fmt(o.price)}</td><td><span className="status">{o.status}</span></td></tr>)}</tbody></table>:<Empty/>}</div></section>}
function Funds({cash,onAdd}){return <section className="page"><div className="page-title"><div><p className="overline">FUNDS</p><h1>Cash & payments</h1><p>Add demo funds through the QR payment flow and view account activity.</p></div><button className="fund" onClick={onAdd}><Plus size={17}/> Add money</button></div><div className="fund-grid"><div className="card balance-card"><div className="metric-icon"><Wallet/></div><p>Available to trade</p><h2>₹{fmt(cash)}</h2><span className="positive">Instant demo balance</span><button className="fund full" onClick={onAdd}><QrCode size={17}/> Add via QR</button></div><div className="card payment-card"><p className="overline">PAYMENT FLOW</p><h2>Fast, simple, familiar.</h2><p>For the MVP, users can scan a QR code and then confirm the demo payment. Replace this with a verified UPI/payment gateway before production.</p><div className="payment-steps"><div><b>01</b><span>Choose amount</span></div><div><b>02</b><span>Scan QR</span></div><div><b>03</b><span>Confirm payment</span></div></div></div></div></section>}
function Modal({type,close,onAdd}){const [amount,setAmount]=useState(5000); const [paymentProof,setPaymentProof]=useState(null); const [uploadStatus,setUploadStatus]=useState(''); const handleProofUpload=async e=>{const file=e.target.files?.[0]; if(!file)return; if(!file.type.startsWith('image/')){setUploadStatus('Please upload an image screenshot.');return} if(file.size>8*1024*1024){setUploadStatus('Screenshot must be smaller than 8 MB.');return} setPaymentProof(file); setUploadStatus('Screenshot attached.');}; 
const submitPayment = async () => {
  const webhook = import.meta.env.VITE_PAYMENT_PROOF_WEBHOOK_URL;

  if (!paymentProof) {
    setUploadStatus('Please upload your payment screenshot first.');
    return;
  }

  if (!webhook) {
    setUploadStatus(
      'Screenshot attached. Add VITE_PAYMENT_PROOF_WEBHOOK_URL to send it to your admin.'
    );
    return;
  }

  try {
    setUploadStatus('Sending payment proof...');

    const fd = new FormData();

    fd.append('payment_screenshot', paymentProof);
    fd.append('amount', String(Number(amount) || 0));
    fd.append('submitted_at', new Date().toISOString());

    const response = await fetch(webhook, {
      method: 'POST',
      body: fd,
    });

    if (!response.ok) {
      throw new Error(`Webhook failed with status ${response.status}`);
    }

    setUploadStatus('Payment screenshot sent successfully.');

    onAdd(Number(amount) || 0);

  } catch (err) {
    console.error('Payment proof submission error:', err);

    setUploadStatus(
      'Could not send the screenshot. Please check your payment connection and try again.'
    );
  }
};if(type==='success')return <div className="overlay"><div className="modal success-modal"><div className="success-mark"><Zap size={28}/></div><h2>Order executed</h2><p>Your paper trade has been recorded successfully.</p><button className="fund full" onClick={close}>Back to dashboard</button></div></div>;if(type==='insufficient')return <div className="overlay"><div className="modal"><button className="close" onClick={close}><X/></button><h2>Insufficient balance</h2><p className="modal-sub">This demo account doesn't have enough available cash for this order.</p><button className="fund full" onClick={()=>{close();}}>Close</button></div></div>;return <div className="overlay"><div className="modal payment-modal"><button className="close" onClick={close}><X/></button><p className="overline">ADD FUNDS</p><h2>Fund your trading wallet</h2><p className="modal-sub">Select an amount, scan the demo QR and confirm payment.</p><div className="amounts">{[500,1000,5000,10000].map(n=><button className={amount===n?'chosen':''} onClick={()=>setAmount(n)} key={n}>₹{n.toLocaleString('en-IN')}</button>)}</div><label className="custom">Custom amount<input type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><div className="qr-box"><div className="qr-art"><img src="/phonepe-qr.png" alt="PhonePe payment QR code" /></div><div><p>SCAN TO PAY</p><h3>₹{Number(amount||0).toLocaleString('en-IN')}</h3><small>Scan this PhonePe QR to make the payment.</small><strong>Payment QR</strong></div></div><div className="payment-proof"><div className="proof-head"><div><b>Upload payment screenshot</b><small>After paying, upload the screenshot here as payment proof.</small></div><label className="upload-proof"><Upload size={16}/> {paymentProof?'Change screenshot':'Choose screenshot'}<input type="file" accept="image/*" onChange={handleProofUpload}/></label></div>{paymentProof&&<div className="proof-preview"><img src={URL.createObjectURL(paymentProof)} alt="Payment screenshot preview"/><div><b>{paymentProof.name}</b><small>{(paymentProof.size/1024/1024).toFixed(2)} MB</small></div><button type="button" className="remove-proof" onClick={()=>{setPaymentProof(null);setUploadStatus();}}>Remove</button></div>}{uploadStatus&&<div className="proof-status">{uploadStatus}</div>}</div><div className="secure-line"><ShieldCheck size={16}/> Your screenshot is submitted as payment proof for admin verification.</div><button className="fund full" onClick={submitPayment}><CheckCircleIcon/> Submit payment proof</button></div></div>}
function CheckCircleIcon(){return <span style={{display:'inline-flex'}}><ShieldCheck size={17}/></span>}

createRoot(document.getElementById('root')).render(<App/>);
